config/routes.rb
Rails.application.routes.draw do

  resources :products
  resources :categories
  get 'landing/index'
  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale
  get 'dashboards/index'

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  match 'dashboard', to: 'dashboards#index', via: [:get]

  root to: "landing#index"

  devise_for :users
  # devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => '/'}

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :uploads, dependent: :destroy
  accepts_attachments_for :uploads, attachment: :avatar, append: true
  has_many :properties
  accepts_nested_attributes_for :properties, :reject_if => :all_blank, :allow_destroy => true
  has_many :attachments, dependent: :destroy
  accepts_nested_attributes_for :attachments, :reject_if => :all_blank, :allow_destroy => true
  accepts_attachments_for :attachments, attachment: :attach
  monetize :price
  monetize :cost_price

  validates_associated :uploads
  validates :category_id, :presence => true
  validates :name, :sku, :presence => true
  validates :price, :numericality => true
  validates :cost_price, :numericality => true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  layout 'dashboards'

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(
        :user_id,
        :name,
        :sku,
        :description,
        :short_description,
        :active,
        :weight,
        :price,
        :cost_price,
        :featured,
        :stock_control,
        :category_id,
        uploads_avatars: [
          :avatar,
          :avatar_cache_id,
          :remove_avatar
        ],
        properties_attributes: [
          :id,
          :product_id,
          :_destroy
        ],
        attachments_attributes: [
          :id,
          :product_id,
          :_destroy,
          :attach,
          :attach_filename,
          :attach_size,
          :file_content_type,
          :attach_cache_id,
          :remove_attach
        ]
      )
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_attachment_fields.html.slim
.row.well.nested-fields.animated.fadeInDown
  .col-lg-10
    = f.file_field :attach, direct: true, presigned: true, progress_class: 'progress-bar-danger'
  .col-lg-2
    .links.animated.flash
      /= link_to_remove_association t("remove attachment"), f, class: "badge badge-danger"
      = link_to_remove_association '<i class="fa fa-trash size-26"></i>'.html_safe, f

app/views/products/_form.html.slim
= stylesheet_link_tag "products", :media => 'all'
= javascript_include_tag 'products'

.wrapper.wrapper-content.animated.fadeInRight.ecommerce
  .row
    .col-lg-12
      = simple_form_for(@product, html: {multipart: true}) do |f|
        = f.error_notification
        .tabs-container
          ul.nav.nav-tabs
            li.active
              a[aria-expanded="true" data-toggle="tab" href="#tab-1"] = t('Product info')
            li
              a[aria-expanded="false" data-toggle="tab" href="#tab-2"] = t('Product description')
            li
              a[aria-expanded="false" data-toggle="tab" href="#tab-3"] = t('Product data')
            li
              a[aria-expanded="false" data-toggle="tab" href="#tab-4"] = t('Upload')
            li
              a[aria-expanded="false" data-toggle="tab" href="#tab-5"] = t('Property')
            li
              a[aria-expanded="false" data-toggle="tab" href="#tab-6"] = t('Attachments')
            li
              .form-actions
                = f.submit t('Save'), class: "btn btn-info btn-block"
          .tab-content
            #tab-1.tab-pane.active
              .panel-body
                fieldset[class="form-horizontal"]
                  .form-group
                    label.col-sm-2.control-label = t('Categories')
                    .col-sm-4
                      .form-inputs
                        = f.association :category, collection: Category.all, label: false, include_blank: false, prompt: t('Choose category')
                  .form-group
                    label.col-sm-2.control-label = t('Name')
                    .col-sm-4
                      .form-inputs
                        = f.input :name, label: false, placeholder: t('Product name')
                  .form-group
                    label.col-sm-2.control-label = t('Product sku')
                    .col-sm-4
                      .form-inputs
                        = f.input :sku, label: false, placeholder: t('Product sku')
                  .form-group
                    label.col-sm-2.control-label = t('Active')
                    .col-sm-1
                      .form-inputs
                        = f.input :active, label: false
                  .form-group
                    label.col-sm-2.control-label = t('Featured')
                    .col-sm-2
                      .form-inputs
                        = f.input :featured, label: false
                  .form-group
                    label.col-sm-2.control-label = t('Stock control')
                    .col-sm-2
                      .form-inputs
                        = f.input :stock_control, label: false
            #tab-2.tab-pane
              .panel-body
                fieldset[class="form-horizontal"]
                  .form-group
                    label.col-sm-2.control-label = t('Description')
                    .col-sm-10
                      .form-inputs
                        = f.input :description, label: t('Name description'), input_html: { class: 'summernote' }
                    br
                    label.col-sm-2.control-label = t('Other description')
                    .col-sm-10
                      .form-inputs
                        = f.input :short_description, label: t('Name short description'), input_html: { class: 'summernote' }
            #tab-3.tab-pane
              .panel-body
                fieldset[class="form-horizontal"]
                  .form-group
                    label.col-sm-2.control-label = t('Weight')
                    .col-sm-2
                      .form-inputs
                        /= f.input :weight, label: t('Name weight')
                        = f.text_field :weight, class: 'form-control', value: "%.2f" % f.object.weight
                  .form-group
                    label.col-sm-2.control-label = t('Price')
                    .col-sm-2
                      .form-inputs
                        /= f.input :price, label: t('Name price')
                        = f.text_field :price, class: 'form-control', value: "%.2f" % f.object.price
                        /= f.text_field :price, :class => 'form-control', :value => (number_with_precision(f.object.price, :precision => 2) || 0)
                        /number_to_currency(amount, unit: '€', precision: 2, format: "%u %n")
                        /= f.text_field :price, class: 'form-control', value: (number_to_currency(amount, unit: '€', precision: 2, format: "%u %n"))
                  .form-group
                    label.col-sm-2.control-label = t('Cost price')
                    .col-sm-2
                      .form-inputs
                        = f.text_field :cost_price, class: 'form-control', value: "%.2f" % f.object.cost_price
            #tab-4.tab-pane
              .panel-body
                .table-responsive
                  table.table.table-bordered.table-stripped
                    thead
                      tr
                        th Image preview
                        th Image url
                        th Sort order
                        th Actions
                    tbody
                      tr
                        td
                          img[src="1_files/2s.jpg"]
                        td
                          input.form-control[disabled="disabled" value="http://mydomain.com/images/image1.png" type="text"]
                        td
                          input.form-control[value="1" type="text"]
                        td
                          button.btn.btn-white
                            i.fa.fa-trash
                      tr
                        td
                          img[src="1_files/1s.jpg"]
                        td
                          input.form-control[disabled="disabled" value="http://mydomain.com/images/image2.png" type="text"]
                        td
                          input.form-control[value="2" type="text"]
                        td
                          button.btn.btn-white
                            i.fa.fa-trash
                      tr
                        td
                          img[src="1_files/3s.jpg"]
                        td
                          input.form-control[disabled="disabled" value="http://mydomain.com/images/image3.png" type="text"]
                        td
                          input.form-control[value="3" type="text"]
                        td
                          button.btn.btn-white
                            i.fa.fa-trash
                      tr
                        td
                          img[src="1_files/4s.jpg"]
                        td
                          input.form-control[disabled="disabled" value="http://mydomain.com/images/image4.png" type="text"]
                        td
                          input.form-control[value="4" type="text"]
                        td
                          button.btn.btn-white
                            i.fa.fa-trash
                      tr
                        td
                          img[src="1_files/5s.jpg"]
                        td
                          input.form-control[disabled="disabled" value="http://mydomain.com/images/image5.png" type="text"]
                        td
                          input.form-control[value="5" type="text"]
                        td
                          button.btn.btn-white
                            i.fa.fa-trash
                      tr
                        td
                          img[src="1_files/6s.jpg"]
                        td
                          input.form-control[disabled="disabled" value="http://mydomain.com/images/image6.png" type="text"]
                        td
                          input.form-control[value="6" type="text"]
                        td
                          button.btn.btn-white
                            i.fa.fa-trash
                      tr
                        td
                          img[src="1_files/7s.jpg"]
                        td
                          input.form-control[disabled="disabled" value="http://mydomain.com/images/image7.png" type="text"]
                        td
                          input.form-control[value="7" type="text"]
                        td
                          button.btn.btn-white
                            i.fa.fa-trash
            /#tab-4.tab-pane
              .panel-body
                fieldset[class="form-horizontal"]
                  .form-group
                    label.col-sm-2.control-label = t('Attachments')
                    .col-sm-10
                      .form-inputs
                        #uploads
                          = f.label :uploads_avatars
                          = f.attachment_field :uploads_avatars, multiple: true
            #tab-5.tab-pane
              .panel-body
                fieldset[class="form-horizontal"]
                  .form-group
                    label.col-sm-2.control-label = t('Property')
                    .col-sm-5
                      .form-inputs
                        #properties
                          = f.simple_fields_for :properties do |property|
                            = render 'property_fields', :f => property
                          .links.animated.fadeInLeft
                            /= link_to_add_association t('add properties'), f, :properties, class: "btn btn-info btn-rounded btn-block"
                            /= link_to_add_association '<i class="fa fa-newspaper-o size-14"></i>'.html_safe  + ' ' +  t('add').html_safe, f, :properties
                            = link_to_add_association f, :properties, data: {:'cocoon-limit' => 3}, class: "btn btn-warning btn-outline fa fa-newspaper-o size-12" do
                              You = t('add')
                              |
                              '
                              b data={counter: ""}
                              items

            #tab-6.tab-pane
              .panel-body
                fieldset[class="form-horizontal"]
                  .form-group
                    label.col-sm-3.control-label = t('Images and Documents')
                    .col-sm-5
                      .form-inputs
                        #properties
                          = f.simple_fields_for :attachments do |attachment|
                            = render 'attachment_fields', :f => attachment
                          .links.animated.fadeInLeft
                            /= link_to_add_association '<i class="fa fa-file-photo-o size-20"></i>'.html_safe  + ' ' +  t('add').html_safe, f, :attachments
                            = link_to_add_association f, :attachments, data: {:'cocoon-limit' => 3}, class: "btn btn-warning btn-outline fa fa-file-photo-o size-12" do
                              You = t('add')
                              |
                              '
                              b data={counter: ""}
                              items
            .col-sm-3
              .links.animated.rotateIn
                = link_to '<i class="fa fa-reply size-14"></i>'.html_safe, products_path
        /.form-group
          .col-sm-7
            .form-actions
              .col-sm-3
                = f.submit t('Save'), class: "btn btn-info btn-block"
              .col-sm-3
                = link_to t('Back'), categories_path, class: "btn btn-info btn-block"
javascript:
  $('#properties').cocoon_limiter()

app/views/products/_property_fields.html.slim
.row.well.nested-fields.animated.fadeInDown
  .col-lg-10
    = f.input :key, label: false, placeholder: t("Property key")
    = f.input :value, label: false, placeholder: t("Property value")
  .col-lg-2
    .links.animated.flash
      /= link_to_remove_association t("remove properties"), f, class: "badge badge-danger"
      = link_to_remove_association '<i class="fa fa-trash size-26"></i>'.html_safe, f

app/views/products/edit.html.slim
.row.wrapper.border-bottom.white-bg.page-heading2
  .col-lg-8
    h2 = t('Editing product')
    ol.breadcrumb
      li
        a[href="#{url_for :controller => 'products', :action => 'index'}"] = t('Product')
      li.active
        strong = t('Edit products')
    br

== render 'form'

/h1 Editing product
/== render 'form'
/= link_to 'Show', @product
/'|
/= link_to 'Back', products_path

app/views/products/index.html.slim
.row.wrapper.border-bottom.white-bg.page-heading2
  .col-lg-8
    h2 = t('Catalog')
    ol.breadcrumb
      li
        a[href="#{url_for :controller => 'products', :action => 'index'}"] = t('Products')
      li.active
        strong = t('Listing products')
  .col-lg-3
    .title-action
      = link_to "<button class='btn btn-sm btn-success dim btn-outline' type='button'>#{t('Create products')}</button>".html_safe, new_product_path
  .col-lg-1

.wrapper.wrapper-content.animated.fadeInRight.ecommerce
  .ibox-content.m-b-sm.border-bottom
    .row
      .col-sm-3
        .form-group
          label.control-label[for="product_name"] = t('Product name')
          input[type="text" id="product_name" name="product_name" value="" placeholder="#{t('Product name')}" class="form-control"]
      .col-sm-4
        .form-group
          label.control-label[for="product_sku"] = t('Product sku')
          input[type="text" id="product_sku" name="product_sku" value="" placeholder="#{t('Product sku')}" class="form-control"]
      .col-sm-2
        .form-group
          label.control-label[for="active"] = t('Active')
          select[name="active" id="active" class="form-control"]
            option[value="1" selected] = t('Enabled')
            option[value="0"] = t('Disabled')

  .row
    .col-lg-12
      .ibox
        .ibox-content
          table.footable.table.table-stripped.toggle-arrow-tiny[data-page-size="15"]
            thead
              tr
                th = t('Name')
                th = t('Category')
                th = t('Sku')
                th = t('Description')
                th = t('Upload')
                th = t('Active')
                th
                th
                th
            tbody
              - @products.each do |product|
                tr
                  td = product.name
                  td = product.category
                  td = product.sku
                  td = product.description.html_safe
                  td
                    - product.uploads.each do |upload|
                      = attachment_image_tag(upload, :avatar, :fill, 50, 50)
                  td.footable-visible
                    - if product.active == true
                      span.label.label-primary = t('Enabled')
                    - else
                      span.label.label-danger = t('Disabled')
                  td = link_to '<i class="fa fa-eye size-14"></i>'.html_safe, product
                  td = link_to '<i class="fa fa-pencil size-14"></i>'.html_safe, edit_product_path(product)
                  td = link_to '<i class="fa fa-trash size-14"></i>'.html_safe, product, data: {:confirm => t('Are you sure')}, :method => :delete

/h1 Listing products

/table
  thead
    tr
      th User
      th Name
      th Sku
      th Description
      th Short description
      th Active
      th Weight
      th Price
      th Cost price
      th Featured
      th Stock control
      th Category
      th
      th
      th

  /tbody
    - @products.each do |product|
      tr
        td = product.user
        td = product.name
        td = product.sku
        td = product.description
        td = product.short_description
        td = product.active
        td = product.weight
        td = product.price
        td = product.cost_price
        td = product.featured
        td = product.stock_control
        td = product.category
        td = link_to 'Show', product
        td = link_to 'Edit', edit_product_path(product)
        td = link_to 'Destroy', product, data: {:confirm => 'Are you sure?'}, :method => :delete

/br

/= link_to 'New Product', new_product_path

app/views/products/new.html.slim
.row.wrapper.border-bottom.white-bg.page-heading2
  .col-lg-8
    h2 = t('New Products')
    ol.breadcrumb
      li
        a[href="#{url_for :controller => 'products', :action => 'index'}"] = t('Products')
      li.active
        strong = t('Create product')
    br

== render 'form'

/h1 New product

/== render 'form'

/= link_to 'Back', products_path

app/views/products/show.html.slim
br
.row.wrapper.animated.fadeInRight
  .col-lg-8
    .ibox.float-e-margins
      .ibox-title
        h5
        .ibox-tools
          a.collapse-link
            i.fa.fa-chevron-up
          a.dropdown-toggle[data-toggle="dropdown" href="#"]
            i.fa.fa-wrench
          ul.dropdown-menu.dropdown-user
            li
              a[href="#"] Config option 1
            li
              a[href="#"] Config option 2
          a.close-link
            i.fa.fa-times
      .ibox-content
        .row
          .col-sm-10
            p
              strong = t('Name')
              | :
              '
              = @product.name
            p
              strong = t('Category')
              | :
              '
              = @product.category
            p
              strong = t('Product sku')
              | :
              '
              = @product.sku
            p
              strong = t('Description')
              | :
              '
              = @product.description.html_safe
            p
              strong = t('Short description')
              | :
              '
              = @product.short_description.html_safe
            p
              - if @product.active == true
                strong = t('Active')
                | :
                '
                span.label.label-primary = t('Enabled')
              - else
                strong = t('Active')
                | :
                '
                span.label.label-danger = t('Disabled')
            p
              strong = t('Weight')
              | :
              '
              = @product.weight
              '
              strong = t('Price')
              | :
              '
              = number_to_currency @product.price
              '
              strong = t('Cost price')
              | :
              '
              = number_to_currency @product.cost_price
            p
              - if @product.featured == true
                strong = t('Featured')
                | :
                '
                span.label.label-success = t('Done')
              - else
                strong = t('Featured')
                | :
                '
                span.label.label-warning = t('None')

              |
              '
              - if @product.stock_control == true
                strong = t('Stock control')
                | :
                '
                span.label.label-success = t('Done')
              - else
                strong = t('Stock control')
                | :
                '
                span.label.label-warning = t('None')
            p
              strong = t('Upload')
              | :
              '
              - @product.uploads.each do |upload|
                = attachment_image_tag(upload, :avatar, :fill, 60, 60)
            p
              strong = t('Images and Documents')
              | :
              '
              - @product.attachments.each do |attachment|
                = attachment_image_tag(attachment, :attach, :fill, 60, 60)
                small
                  ul
                    li
                      = attachment.attach_content_type
                    li
                      = attachment.attach_filename
                    li
                      = attachment.attach_size
                      '
                      | Bytes

  .col-lg-4
    = link_to t('Edit'), edit_product_path(@product), class: "btn btn-info"
    '
    = link_to t('Back'), products_path, class: "btn btn-info"

/p#notice = notice
/
/p
  strong User:
  = @product.user
/p
  strong Name:
  = @product.name
/p
  strong Sku:
  = @product.sku
/p
  strong Description:
  = @product.description.html_safe
/p
  strong Short description:
  = @product.short_description.html_safe
/p
  strong Active:
  = @product.active
/p
  strong Weight:
  = @product.weight
/p
  strong Price:
  = @product.price
/p
  strong Cost price:
  = @product.cost_price
/p
  strong Featured:
  = @product.featured
/p
  strong Stock control:
  = @product.stock_control
/p
  strong Category:
  = @product.category
/p
  - @product.uploads.each do |upload|
    = attachment_image_tag(upload, :avatar, :fill, 100, 100)
/p


/= link_to 'Edit', edit_product_path(@product)
/'|
/= link_to 'Back', products_path