config/routes.rb
Rails.application.routes.draw do

  resources :products
  resources :categories
  get 'landing/index'
  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale
  get 'dashboards/index'

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  match 'dashboard', to: 'dashboards#index', via: [:get]

  root to: "landing#index"

  devise_for :users
  # devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => '/'}

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :product
  attachment :attach
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  def to_s
    "#{name}"
  end
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :uploads, dependent: :destroy
  accepts_attachments_for :uploads, attachment: :avatar, append: true
  has_many :properties
  accepts_nested_attributes_for :properties, :reject_if => :all_blank, :allow_destroy => true
  has_many :attachments, dependent: :destroy
  accepts_nested_attributes_for :attachments, :reject_if => :all_blank, :allow_destroy => true
  accepts_attachments_for :attachments, attachment: :attach
  monetize :price
  monetize :cost_price

  validates_associated :uploads
  validates :category_id, :presence => true
  validates :name, :sku, :presence => true
  validates :price, :numericality => true
  validates :cost_price, :numericality => true
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :product
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  belongs_to :product
  attachment :avatar
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :dashboards
  has_many :products

  attachment :avatar

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  layout 'dashboards'

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :displayed)
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  layout 'dashboards', only: [:index]

  def index
    @users = User.all
    # @dashboards = current_user.dashboards
  end

  # private
  # def dashboard_params
  #   params.require(:dashboard).permit(:user_id)
  # end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  before_filter :authenticate_user!, except: [:show]
  layout 'errors', only: [:show]

  def show
    render status_code.to_s, :status => status_code
  end

  protected

  def status_code
    params[:code] || 500
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  layout 'landing', only: [:index]

  def index; end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  layout 'dashboards'

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(
        :user_id,
        :name,
        :sku,
        :description,
        :short_description,
        :active,
        :weight,
        :price,
        :cost_price,
        :featured,
        :stock_control,
        :category_id,
        uploads_avatars: [
          :avatar,
          :avatar_cache_id,
          :remove_avatar
        ],
        properties_attributes: [
          :id,
          :product_id,
          :_destroy
        ],
        attachments_attributes: [
          :id,
          :product_id,
          :_destroy,
          :attach,
          :attach_filename,
          :attach_size,
          :file_content_type,
          :attach_cache_id,
          :remove_attach
        ]
      )
    end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_filter :authenticate_user!, except: [:change_locale]
  layout 'authorization'

  def change_locale
    l = params[:locale].to_s.strip.to_sym
    l = I18n.default_locale unless I18n.available_locales.include?(l)
    cookies.permanent[:FnfZettheme_locale] = l
    redirect_to request.referer || root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
  def alert_class_for(flash_type)
    {
      :success => 'alert-success',
      :error => 'alert-danger',
      :alert => 'alert-warning',
      :notice => 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/layouts/_dashboards_chat_box.html.erb
<div class="small-chat-box fadeInRight animated">
  <div class="heading" draggable="true">
    <small class="chat-date pull-right">02.19.2015</small>Small chat
  </div>
  <div style="position: relative; overflow: hidden; width: auto; height: 234px;" class="slimScrollDiv">
    <div style="overflow: hidden; width: auto; height: 234px;" class="content">
      <div class="left">
        <div class="author-name">Monica Jackson <small class="chat-date">10:02 am</small></div>
        <div class="chat-message active">Lorem Ipsum is simply dummy text input.</div>
      </div>
      <div class="right">
        <div class="author-name">Mick Smith<small class="chat-date">11:24 am</small></div>
        <div class="chat-message">Lorem Ipsum is simpl.</div>
      </div>
      <div class="left">
        <div class="author-name">Alice Novak<small class="chat-date">08:45 pm</small></div>
        <div class="chat-message active">Check this stock char.</div>
      </div>
      <div class="right">
        <div class="author-name">Anna Lamson<small class="chat-date">11:24 am</small></div>
        <div class="chat-message">The standard chunk </div>
      </div>
    </div>
    <div style="background: rgb(0, 0, 0) none repeat scroll 0% 0%; width: 7px; position: absolute; top: 0px; opacity: 0.4; display: block; border-radius: 7px; z-index: 99; right: 1px;" class="slimScrollBar"></div>
    <div style="width: 7px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; background: rgb(51, 51, 51) none repeat scroll 0% 0%; opacity: 0.4; z-index: 90; right: 1px;" class="slimScrollRail"></div>
  </div>
  <div class="form-chat">
    <div class="input-group input-group-sm">
      <input class="form-control" type="text">
      <span class="input-group-btn">
        <button class="btn btn-primary" type="button">Send</button>
      </span>
    </div>
  </div>
</div>

<div id="small-chat">
  <span class="badge badge-warning pull-right">5</span>
  <a class="open-small-chat"><i class="fa fa-comments"></i></a>
</div>

app/views/layouts/_dashboards_footer.html.slim
.footer
  .pull-right
    div
      strong
        | Zettheme Inc. &copy; 2015
  div
    strong
      = I18n.localize(Date.today, :format => :long)

app/views/layouts/_dashboards_navigation.html.slim
nav.navbar-default.navbar-static-side[role="navigation"]
  .sidebar-collapse
    ul.nav#side-menu
      li.nav-header
        .dropdown.profile-element
          - if current_user.avatar_id?
          span
            = image_tag attachment_url(current_user, :avatar, :fill, 80, 80), class: 'img-circle'
          a[data-toggle="dropdown" class="dropdown-toggle" href="#"]
            span.clear
              span.block.m-t-xs
                - if current_user.avatar_id?
                  strong.font-bold = current_user.name
              span.text-muted.text-xs.block.size8
                '
                = t('Avatar menu')
                '
                b.caret
          ul.dropdown-menu.animated.fadeInRight.m-t-xs
            li
              a[href="profile.html"] = t('Profile')
            li
              a[href="contacts.html"] = t('Contacts')
            li
              a[href="mailbox.html"] = t('Mailbox')
            li.divider
            li = link_to t('Logout'), destroy_user_session_path, :method=>'delete'
        .logo-element FnF
      /li.active
      li
        a[href="#{url_for :controller => 'dashboards', :action => 'index'}"]
          i.fa.fa-th-large
          span.nav-label = t('Dashboards')
          span.fa.arrow
        ul.nav.nav-second-level
          li.active
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Widgets')
      li
        a[href="#{url_for :controller => 'dashboards', :action => 'index'}"]
          i.fa.fa-th-large
          span.nav-label = t('Catalog')
          span.fa.arrow
        ul.nav.nav-second-level
          li
            a[href="#{url_for :controller => 'categories', :action => 'index'}"] = t('Categories')
          li
            a[href="#{url_for :controller => 'products', :action => 'index'}"] = t('Products')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Monitoring')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Product Attributes')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Product Features')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Manufacturers')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Suppliers')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Tags')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Attachments')
      li
        a[href="#{url_for :controller => 'dashboards', :action => 'index'}"]
          i.fa.fa-th-large
          span.nav-label = t('Orders')
          span.fa.arrow
        ul.nav.nav-second-level
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Orders')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Invoices')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Merchandise Returns')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Delivery Slips')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Credit Slips')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Statuses')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Order Messages')
      li
        a[href="#{url_for :controller => 'dashboards', :action => 'index'}"]
          i.fa.fa-th-large
          span.nav-label = t('Customers')
          span.fa.arrow
        ul.nav.nav-second-level
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Custommers')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Addresses')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Groups')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Shopping Charts')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Customer Service')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Contacts')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Titles')
      li
        a[href="#{url_for :controller => 'dashboards', :action => 'index'}"]
          i.fa.fa-th-large
          span.nav-label = t('Price Rules')
          span.fa.arrow
        ul.nav.nav-second-level
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Cart Rules')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Catalog Price Rules')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Marketing')
      li
        a[href="#{url_for :controller => 'dashboards', :action => 'index'}"]
          i.fa.fa-globe
          span.nav-label = t('Localizations')
          span.fa.arrow
        ul.nav.nav-second-level
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"]
              span.nav-label = t('menu.panels.lang')
              span.fa.arrow
            ul.nav.nav-second-level
              li = link_to t('menu.panels.en'), change_locale_path(:en)
              li = link_to t('menu.panels.ru'), change_locale_path(:ru)
              li = link_to t('menu.panels.uk'), change_locale_path(:uk)
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Zones')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Countries')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('States')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Currencies')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Taxes')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Tax Rules')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Translations')
      li
        a[href="#{url_for :controller => 'dashboards', :action => 'index'}"]
          i.fa.fa-th-large
          span.nav-label = t('Preferences')
          span.fa.arrow
        ul.nav.nav-second-level
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('General')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Orders')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Products')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Customers')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('CMS')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Images')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Store Contacts')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Search')
      li
        a[href="#{url_for :controller => 'dashboards', :action => 'index'}"]
          i.fa.fa-th-large
          span.nav-label = t('Administration')
          span.fa.arrow
        ul.nav.nav-second-level
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Preferences')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Quick Access')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Employsees')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Profiles')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Permissions')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Manage roles')
      li
        a[href="#{url_for :controller => 'dashboards', :action => 'index'}"]
          i.fa.fa-th-large
          span.nav-label = t('Stats')
          span.fa.arrow
        ul.nav.nav-second-level
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Stats')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Search Engines')
          li
            a[href="#{url_for :controller => 'dashboards', :action => 'index'}"] = t('Referrers')
      li.landing_link
        a[target="_blank" href="#{url_for :controller => 'landing', :action => 'index'}"]
          i.fa.fa-google
          span.nav-label = t('Landing Page')
          span.label.label-warning.pull-right
      li.special_link
        a[target="_blank" href="http://emberjs.com"]
          i.fa.fa-star
          span.nav-label Ember Ambitious Web

app/views/layouts/_dashboards_right_sidebar.html.erb
<div id="right-sidebar">
  <div style="position: relative; overflow: hidden; width: auto; height: 100%;" class="slimScrollDiv">
    <div style="overflow: hidden; width: auto; height: 100%;" class="sidebar-container">
      <ul class="nav nav-tabs navs-3">
        <li class="active"><a data-toggle="tab" href="#tab-1">Notes</a></li>
        <li><a data-toggle="tab" href="#tab-2">Projects</a></li>
        <li class=""><a data-toggle="tab" href="#tab-3"><i class="fa fa-gear"></i></a></li>
      </ul>
      <div class="tab-content">
        <div id="tab-1" class="tab-pane active">
          <div class="sidebar-title">
            <h3><i class="fa fa-comments-o"></i> Latest Notes</h3>
            <small><i class="fa fa-tim"></i> You have 10 new message.</small>
        </div>
        <div>
          <div class="sidebar-message">
            <a href="#">
              <div class="pull-left text-center">
                <img alt="image" class="img-circle message-avatar" src="INSPINIA%20%7C%20Dashboard_files/a1.jpg">
                <div class="m-t-xs">
                  <i class="fa fa-star text-warning"></i>
                  <i class="fa fa-star text-warning"></i>
                </div>
              </div>
              <div class="media-body">
                There are many variations of passages of Lorem Ipsum available.
                <br>
                <small class="text-muted">Today 4:21 pm</small>
              </div>
            </a>
          </div>
        </div>
      </div>
      <div id="tab-2" class="tab-pane">
        <div class="sidebar-title">
          <h3> <i class="fa fa-cube"></i> Latest projects</h3>
          <small><i class="fa fa-tim"></i> You have 14 projects. 10 not completed.</small>
        </div>
        <ul class="sidebar-list">
          <li>
            <a href="#">
              <div class="small pull-right m-t-xs">9 hours ago</div>
              <h4>Business valuation</h4>
              It is a long established fact that a reader will be distracted.
              <div class="small">Completion with: 22%</div>
              <div class="progress progress-mini">
                <div style="width: 22%;" class="progress-bar progress-bar-warning"></div>
              </div>
              <div class="small text-muted m-t-xs">Project end: 4:00 pm - 12.06.2014</div>
            </a>
          </li>
          <li>
            <a href="#">
              <div class="small pull-right m-t-xs">9 hours ago</div>
              <h4>Contract with Company </h4>
              Many desktop publishing packages and web page editors.
              <div class="small">Completion with: 48%</div>
              <div class="progress progress-mini">
                <div style="width: 48%;" class="progress-bar"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="label label-primary pull-right">NEW</span>
              <h4>The generated</h4>
              <!--<div class="small pull-right m-t-xs">9 hours ago</div>-->
              There are many variations of passages of Lorem Ipsum available.
              <div class="small">Completion with: 22%</div>
              <div class="small text-muted m-t-xs">Project end: 4:00 pm - 12.06.2014</div>
            </a>
          </li>
        </ul>
      </div>
      <div id="tab-3" class="tab-pane">
        <div class="sidebar-title">
          <h3><i class="fa fa-gears"></i> Settings</h3>
          <small><i class="fa fa-tim"></i> You have 14 projects. 10 not completed.</small>
        </div>
        <div class="setings-item">
          <span>Show notifications</span>
          <div class="switch">
            <div class="onoffswitch">
              <input name="collapsemenu" class="onoffswitch-checkbox" id="example" type="checkbox">
              <label class="onoffswitch-label" for="example">
                <span class="onoffswitch-inner"></span>
                <span class="onoffswitch-switch"></span>
              </label>
            </div>
          </div>
        </div>
        <div class="setings-item">
          <span>Disable Chat</span>
          <div class="switch">
            <div class="onoffswitch">
              <input name="collapsemenu" checked="checked" class="onoffswitch-checkbox" id="example2" type="checkbox">
              <label class="onoffswitch-label" for="example2">
                <span class="onoffswitch-inner"></span>
                <span class="onoffswitch-switch"></span>
              </label>
            </div>
          </div>
        </div>
        <div class="setings-item">
          <span>Enable history</span>
          <div class="switch">
            <div class="onoffswitch">
              <input name="collapsemenu" class="onoffswitch-checkbox" id="example3" type="checkbox">
              <label class="onoffswitch-label" for="example3">
                <span class="onoffswitch-inner"></span>
                <span class="onoffswitch-switch"></span>
              </label>
            </div>
          </div>
        </div>
        <div class="setings-item">
          <span>Show charts</span>
          <div class="switch">
            <div class="onoffswitch">
              <input name="collapsemenu" class="onoffswitch-checkbox" id="example4" type="checkbox">
              <label class="onoffswitch-label" for="example4">
                <span class="onoffswitch-inner"></span>
                <span class="onoffswitch-switch"></span>
              </label>
            </div>
          </div>
        </div>
        <div class="setings-item">
          <span>Offline users</span>
          <div class="switch">
            <div class="onoffswitch">
              <input checked="checked" name="collapsemenu" class="onoffswitch-checkbox" id="example5" type="checkbox">
              <label class="onoffswitch-label" for="example5">
                <span class="onoffswitch-inner"></span>
                <span class="onoffswitch-switch"></span>
              </label>
            </div>
          </div>
        </div>
        <div class="setings-item">
          <span>Global search</span>
          <div class="switch">
            <div class="onoffswitch">
              <input checked="checked" name="collapsemenu" class="onoffswitch-checkbox" id="example6" type="checkbox">
              <label class="onoffswitch-label" for="example6">
                <span class="onoffswitch-inner"></span>
                <span class="onoffswitch-switch"></span>
              </label>
            </div>
          </div>
        </div>
        <div class="setings-item">
          <span>Update everyday</span>
          <div class="switch">
            <div class="onoffswitch">
              <input name="collapsemenu" class="onoffswitch-checkbox" id="example7" type="checkbox">
              <label class="onoffswitch-label" for="example7">
                <span class="onoffswitch-inner"></span>
                <span class="onoffswitch-switch"></span>
              </label>
            </div>
          </div>
        </div>
        <div class="sidebar-content">
          <h4>Settings</h4>
          <div class="small">
            I belive that. Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            And typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever
            since the 1500s. Over the years, sometimes by accident, sometimes on purpose (injected
            humour and the like).
          </div>
        </div>
      </div>
    </div>
  </div>
  <div style="background: rgb(0, 0, 0) none repeat scroll 0% 0%; width: 7px; position: absolute; top: 0px; opacity: 0.4; display: block; border-radius: 7px; z-index: 99; right: 1px; height: 573.309px;" class="slimScrollBar"></div>
  <div style="width: 7px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; background: rgb(51, 51, 51) none repeat scroll 0% 0%; opacity: 0.4; z-index: 90; right: 1px;" class="slimScrollRail"></div>
</div></div>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Fnf Zettheme'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'FnF Zettheme'}"
    == stylesheet_link_tag "application", :media => 'all'
    == javascript_include_tag 'application'
    == csrf_meta_tags
  body
    = yield

app/views/layouts/authorization.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Fnf Zettheme'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'FnF Zettheme'}"
    == stylesheet_link_tag "authorization", :media => 'all'
    == javascript_include_tag 'authorization'
    == csrf_meta_tags
  body.gray-bg.pace-done
    = yield

app/views/layouts/dashboards.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Fnf Zettheme'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'FnF Zettheme'}"
    == stylesheet_link_tag "dashboards", :media => 'all'
    == javascript_include_tag 'dashboards'
    == javascript_include_tag 'cocoon'
    /== javascript_include_tag 'cocoon-limiter/cocoon_limiter.js'
    == csrf_meta_tags
  body.pace-done
    #wrapper
      == render 'layouts/dashboards_navigation'
    #page-wrapper.gray-bg
      == render 'layouts/dashboards_topnavbar'
      == yield
      == render 'shared/flash_messages', flash: flash
      == render 'layouts/dashboards_footer'
      == render 'layouts/dashboards_right_sidebar'
      == render 'layouts/dashboards_chat_box'
      == render 'layouts/dashboards_skinconfig'